name: Forked from official SonarQube Scan
description: >
  Scan your code with SonarQube to detect Bugs, Vulnerabilities and Code Smells in up to 27 programming languages!
branding:
  icon: check
  color: green
runs:
  using: 'composite'
  steps:
    - name: Checkout repo source
      uses: actions/checkout@v4
      with:
          repository: 'VincentDeCasterSonos/sonarqube-scan-action'
          ref: 'image-change' 
          path: 'sonarqube-scan-action'
    - name: List directory contents
      run: ls -la
      shell: bash
      working-directory: sonarqube-scan-action
    - name: Build Docker Image
      run: docker build --build-arg INPUT_BASEIMAGE=${{ inputs.baseImage }} -t custom-image .
      shell: bash
      working-directory: sonarqube-scan-action
    - name: Run Docker Image
      run: docker run -e SONAR_HOST_URL -e SONAR_TOKEN custom-image /cleanup.sh
      shell: bash
      working-directory: sonarqube-scan-action

inputs:
  args:
    description: Additional arguments to the sonar-scanner
    required: false
  projectBaseDir:
    description: Set the sonar.projectBaseDir analysis property
    required: false
    default: .
  baseImage:
    required: false
    description: 'Provide a base image of sonarsource/sonar-scanner-cli that is hosted on your own registry'
 
