name: Forked from official SonarQube Scan
description: >
  Scan your code with SonarQube to detect Bugs, Vulnerabilities and Code Smells in up to 27 programming languages!
branding:
  icon: check
  color: green
runs:
  using: 'composite'
  steps:
    - name: List directory contents
      run: ls -la
      shell: bash
    - name: Build Docker Image
      run: docker build --build-arg INPUT_BASEIMAGE=${{ inputs.baseImage }} -t custom-image -f $GITHUB_WORKSPACE/Dockerfile $GITHUB_WORKSPACE
      shell: bash
    - name: Run Docker Image
      run: docker run --entrypoint /entrypoint.sh custom-image /cleanup.sh
      shell: bash
inputs:
  args:
    description: Additional arguments to the sonar-scanner
    required: false
  projectBaseDir:
    description: Set the sonar.projectBaseDir analysis property
    required: false
    default: .
  baseImage:
    required: false
    description: 'Provide a base image of sonarsource/sonar-scanner-cli that is hosted on your own registry'
 
